export { adaptWebsiteStructureToEditorDocument } from "./adapter";
export {
  getEditorDocumentProjectabilityIssues,
  projectEditorDocumentNavigation,
  projectEditorDocumentSeo,
  projectEditorDocumentToWebsiteStructure,
  trustedWebsiteStructureState,
  type EditorProjectionIssue,
  type EditorProjectionIssueCode,
  type EditorProjectionResult,
  type TrustedWebsiteStructureState,
  type WebsiteSeoArtifactProjection,
} from "./projection";
export { validateEditorDocument } from "./validation";
export { validateEditorDocumentRegistry } from "@/lib/editor/registry";
export {
  EDITOR_DOCUMENT_SCHEMA_VERSION,
  type AlignmentToken,
  type ColumnToken,
  type ContainerToken,
  type DocumentOpenGraph,
  type DocumentPageSeo,
  type DocumentSiteSeo,
  type EditorAssetId,
  type EditorAssetReference,
  type EditorDocument,
  type EditorDocumentCompatibilityMetadata,
  type EditorDocumentId,
  type EditorDocumentSchemaVersion,
  type EditorDocumentSiteSettings,
  type EditorDocumentValidationError,
  type EditorGlobalComponent,
  type EditorNavigationItem,
  type EditorNavigationMenu,
  type EditorNavigationModel,
  type EditorNavigationTarget,
  type EditorNode,
  type EditorNodeId,
  type EditorPage,
  type EditorPageId,
  type EditorReusableComponent,
  type EditorScalar,
  type EditorSlot,
  type EditorSymbolId,
  type EditorSymbolReference,
  type EditorValue,
  type EditorValueObject,
  type LegacyNodeMetadata,
  type NodeStyleTokens,
  type PageNavigationIntent,
  type PageStyleTokens,
  type ResponsiveVisibility,
  type SiteStyleTokens,
  type SpacingToken,
  type ThemeModeToken,
  type ToneToken,
  type VisualStyleToken,
  type WidthToken,
} from "./types";
